# Generated by Django 5.1.2 on 2024-12-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gowesin', '0002_stasiun_url_lokasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='durasi_jam',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
